title: DemonWolfDev
email: demonwolf@demonwolfdev.com
default_lang: eng
author:
  name: Nathan Henniges
  email: 'demonwolf@demonwolfdev.com'
  type: Organization
  jobtitle: Founder
  foundingDate: 2014
  nationality: American
  url: https://www.keybase.com/mrdemonwolf/
metadata:
    description: 'Are you passionate about tech, computers, creativity, and gaming? Grow with our community towards your goals. Join us today!'
    keywords: community,gaming,twitch,youtube,discord
    generator:
GoogleAnalytics: UA-104966812-1
menu:
  -
    title: Discord
    url: 'https://discordapp.com/invite/A9x3qEN'
  -
    title: Support
    url: 'https://streamlabs.com/demonwolfdev'

social:
  -
    class: fab fa-twitch twitch-color
    url: 'https://www.twitch.tv/demonwolfdev'
  -
    class: fab fa-youtube color youtube-color
    url: `https://www.yotube.com/DemonWolfDevOfficial`
  -
    class: fab fa-google-plus-g google_plus-color
    url: 'http://plus.google.com/+DemonWolfDevOfficial'
  -
    class: fab fa-twitter twitter-color
    url: 'https://www.twitter.com/demonwolfdev'
